### ISSUE TITLE
Redo Button

### ISSUE THREAD

**Issue by Dreamurrrr** [Bryantdl7/darkstormdev#101]
Self explanatory. Insanely useful.
https://steamcommunity.com/sharedfiles/filedetails/?id=796294821

**Comment by Bryantdl7** [comment]
I see a lot of comments saying this addon could cause crashes. I will consider this one still, but I will focus on others first.

**Comment by Dreamurrrr** [comment]
"Caveats

• Cannot redo constraints
• Issues when redoing nextbots. Usually causes a crash"
@Bryantdl7

**Comment by Bryantdl7** [comment]
Yes, that is from the description. I’m referring to the comments and saying that big wire contraptions can cause issues as well.

Sent from my iPhone

On Sep 5, 2019, at 9:57 AM, David <notifications@github.com<mailto:notifications@github.com>> wrote:


"Caveats

• Cannot redo constraints
• Issues when redoing nextbots. Usually causes a crash"
@Bryantdl7<https://github.com/Bryantdl7>

**Comment by Dreamurrrr** [comment]
Ah ok

**Comment by Zafiro2232** [comment]
Neat, but bad idea for the same reason duplicator is restricted.
