### ISSUE TITLE
gm_bluehills_test3

### ISSUE THREAD

**Issue by Dreamurrrr** [Bryantdl7/darkstormdev#104]
Best map in my opinion. People complained it is "laggy," but I used it as a primary map on my server and it was fine.
https://steamcommunity.com/sharedfiles/filedetails/?id=243902601

**Comment by Bryantdl7** [comment]
This should already be on the server.

**Comment by Dreamurrrr** [comment]
Hm, idk.

**Comment by Dreamurrrr** [comment]
Woops ignore that.
