### ISSUE TITLE
SprayMesh

### ISSUE THREAD

**Issue by Dreamurrrr** [Bryantdl7/darkstormdev#105]
Idk, for some reason a lot of servers use this. 
https://steamcommunity.com/sharedfiles/filedetails/?id=394091909

**Comment by Dreamurrrr** [comment]
Also author abandoned the project so idk lol

**Comment by InvidiousVoid** [comment]
Do not use!! Unable to make anything my spray.

**Comment by Bryantdl7** [comment]
It seems like this addon isn’t being maintained at all any more. Unless we had a volunteer to upkeep this addon I am hesitant just based on what is shown in the recent comments.

**Comment by Dreamurrrr** [comment]
Looking at the comments and constant issues people are getting from using this add-on, I don't think it would be wise to have this in the server anymore. It hasn't been updated for 4 years and the author does not maintain it, nor provide support anymore. Plus it is just annoying to have to upload your decail to a third-party just so you can use it in the server. Closing.

**Comment by Dreamurrrr** [comment]
People also reported massive performance issues.

**Comment by Dreamurrrr** [comment]
It's in the server anyways xd
