### ISSUE TITLE
precion align error

### ISSUE THREAD

**Issue by Bryantdl7** [Bryantdl7/darkstormdev#11]
[ERROR] addons/wenlis tools/lua/weapons/gmod_tool/stools/precision_align.lua:403: attempt to call global 'PA_DrawToolScreen' (a nil value)
  1. DrawToolScreen - addons/wenlis tools/lua/weapons/gmod_tool/stools/precision_align.lua:403
   2. unknown - gamemodes/sandbox/entities/weapons/gmod_tool/cl_viewscreen.lua:69

uploading in a moment

**Comment by Zafiro2232** [comment]
Might've found a fix, going to test in sp.

**Comment by Bryantdl7** [comment]
Found a new version which fixed this
