### ISSUE TITLE
Scoreboard abbreviating

### ISSUE THREAD

**Issue by Bryantdl7** [Bryantdl7/darkstormdev#13]
line 171 of the scoreboard file shows how to do it

**Comment by Zafiro2232** [comment]
Where are you going to transfer the scoreboard, can't be here or its pretty much being leaked & I don't think the original owner would be too happy with that.

**Comment by Zafiro2232** [comment]
Could you upload or pm me garrysmod/data/ulib/groups.txt so I can properly do this?

**Comment by Bryantdl7** [comment]
I found a way for the plugin to do it, itself. No worries.
