### ISSUE TITLE
MafiaII Simfphys Vehicles

### ISSUE THREAD

**Issue by Bonnie603** [Bryantdl7/darkstormdev#132]
https://steamcommunity.com/sharedfiles/filedetails/?id=1238235086

Nice Vehicle Models & Sounds, Or A Little More Diverse Choices.

**Comment by Bonnie603** [comment]
Cool vehicles and sounds is the only good reason i can think of

**Comment by Zafiro2232** [comment]
Added separately to the server collection, need to manually subscribe if you want to see them.
