### ISSUE TITLE
ADDON REQUEST: Team Fortress 2 Weapons Pack

### ISSUE THREAD

**Issue by Velcroisntniceiguess** [Bryantdl7/darkstormdev#133]
Addon Request: Team Fortress 2 Weapons Pack
URL: https://steamcommunity.com/sharedfiles/filedetails/?id=949733637
Size: 49.229 MB
Reason for Suggestion:
Currently On Darkstorm, We dont have many weapon choices; We have some M9K weapons, some CS weapons, ETC. Team fortress 2 has a Large Variety of weapons, From the ever-present Shotgun, to the less Common Rocket Launcher. I believe that Darkstorm Would Largely Benefit from More weapon choices, The full List of weapons are as follows:

Bat, Bonesaw, Bottle, Fire Axe, Fists, Flame Thrower, Grenade Launcher, Invis Watch, Knife, Kukri
Medi Gun, Minigun, Pistol ( for Scout and Engineer ), Revolver, Rocket Launcher, Scattergum
Shotgun ( for Soldier, Pyro, Heavy, Engineer ), Shovel, SMG, Sniper Rifle, Stickybomb Launcher
Syringe Gun, And Wrench.

**Comment by Zafiro2232** [comment]
Added but all weapons are in limbo right now due to the excess of stuff we have.
