### ISSUE TITLE
Bucket/racing seats for cars addon 

### ISSUE THREAD

**Issue by sakuya69420** [Bryantdl7/darkstormdev#134]
the Race car bucket seat is a great add on to have on dark storm because it is a build server, The racing seats come with the Jeep animation when your sitting on and they aren’t overly the top huge so they can fit inside your car/tank without clipping or looking ugly. https://steamcommunity.com/sharedfiles/filedetails/?id=471435979

**Comment by Zafiro2232** [comment]
Forgot to close.
