### ISSUE TITLE
localized gravity tool mod

### ISSUE THREAD

**Issue by Pato0101** [Bryantdl7/darkstormdev#135]
https://steamcommunity.com/sharedfiles/filedetails/?id=531849338

good addon,great for bulding ships,submarines,and even cars,...kinda?
anyways i think it would be a good addition to the server because well,its a build server,and we build
that stuff in it

im pretty sure it was removed in the addon purge,i really liked it when it was on the server,10/10
would have again

**Comment by Zafiro2232** [comment]
Re-added.
