### ISSUE TITLE
2 of gredwitches collections

### ISSUE THREAD

**Issue by lorahart2** [Bryantdl7/darkstormdev#138]
https://steamcommunity.com/sharedfiles/filedetails/?id=1581186783 https://steamcommunity.com/sharedfiles/filedetails/?id=1887339485 https://steamcommunity.com/sharedfiles/filedetails/?id=1391460275
These are well made ww2 themed vehicle mods and emplacements they are realistic and fun.

**Comment by Zafiro2232** [comment]
I like these personally but the server crashes every 2-3h when gredwitch is being used.
