### ISSUE TITLE
Management Meeting Tasks

### ISSUE THREAD

**Issue by Zafiro2232** [Bryantdl7/darkstormdev#145]
add PS,
clear ps db,
reduce points while afk,
diagnose wuma loadouts to use with ps,
svn acf/advdupe,
mount HL:S, HL2:EP2
sherlock
forum link ingame
LTAP Rejailing
Tpa
benchmark fresh join times
maps to fastdl
SSD space from NFO
replace SQLite with SQL
realtime zones,
tpa
clean bryants desk
big one time purchases for ps(winchester,orb)

**Comment by Bryantdl7** [comment]
assigning you this task to make a bunch of enhancement tasks for each of these.
