### ISSUE TITLE
[pointshop]

### ISSUE THREAD

**Issue by Bryantdl7** [Bryantdl7/darkstormdev#15]
12:34:25 [ERROR] addons/pointshop/lua/pointshop/items/weapons/deagle.lua:1: attempt to index global 'bITEM' (a nil value)
           1. unknown - addons/pointshop/lua/pointshop/items/weapons/deagle.lua:1
            2. include - [C]:-1
             3. LoadItems - addons/pointshop/lua/pointshop/sh_init.lua:119
              4. Initialize - addons/pointshop/lua/pointshop/sh_init.lua:55
               5. unknown - addons/pointshop/lua/autorun/pointshop.lua:4
         
         
12:34:25 L 10/29/2015 - 11:34:14: Lua Error: [POINTSHOP] Item missing name: weapons/Deagle.lua
12:34:25 
12:34:25 L 10/29/2015 - 11:34:14: Lua Error: 
12:34:25 [ERROR] addons/pointshop/lua/pointshop/items/weapons/m24.lua:1: attempt to index global 'bITEM' (a nil value)
           1. unknown - addons/pointshop/lua/pointshop/items/weapons/m24.lua:1
            2. include - [C]:-1
             3. LoadItems - addons/pointshop/lua/pointshop/sh_init.lua:119
              4. Initialize - addons/pointshop/lua/pointshop/sh_init.lua:55
               5. unknown - addons/pointshop/lua/autorun/pointshop.lua:4
         
         
12:34:25 L 10/29/2015 - 11:34:14: Lua Error: [POINTSHOP] Item missing name: weapons/M24.lua

**Comment by Bryantdl7** [comment]
10/29/2015 - 11:39:29: Lua Error: 
[ERROR] addons/pointshop/lua/pointshop/items/weapons/deagle.lua:1: attempt to index global 'bITEM' (a nil value)
  1. unknown - addons/pointshop/lua/pointshop/items/weapons/deagle.lua:1
   2. include - [C]:-1
    3. LoadItems - addons/pointshop/lua/pointshop/sh_init.lua:119
     4. Initialize - addons/pointshop/lua/pointshop/sh_init.lua:55
      5. unknown - addons/pointshop/lua/autorun/pointshop.lua:4



[ERROR] addons/pointshop/lua/pointshop/items/weapons/deagle.lua:1: attempt to index global 'bITEM' (a nil value)
  1. unknown - addons/pointshop/lua/pointshop/items/weapons/deagle.lua:1
   2. include - [C]:-1
    3. LoadItems - addons/pointshop/lua/pointshop/sh_init.lua:119
     4. Initialize - addons/pointshop/lua/pointshop/sh_init.lua:55
      5. unknown - addons/pointshop/lua/autorun/pointshop.lua:4

L 10/29/2015 - 11:39:29: Lua Error: [POINTSHOP] Item missing name: weapons/Deagle.lua

[POINTSHOP] Item missing name: weapons/Deagle.lua
L 10/29/2015 - 11:39:29: Lua Error: 
[ERROR] addons/pointshop/lua/pointshop/items/weapons/m24.lua:1: attempt to index global 'bITEM' (a nil value)
  1. unknown - addons/pointshop/lua/pointshop/items/weapons/m24.lua:1
   2. include - [C]:-1
    3. LoadItems - addons/pointshop/lua/pointshop/sh_init.lua:119
     4. Initialize - addons/pointshop/lua/pointshop/sh_init.lua:55
      5. unknown - addons/pointshop/lua/autorun/pointshop.lua:4



[ERROR] addons/pointshop/lua/pointshop/items/weapons/m24.lua:1: attempt to index global 'bITEM' (a nil value)
  1. unknown - addons/pointshop/lua/pointshop/items/weapons/m24.lua:1
   2. include - [C]:-1
    3. LoadItems - addons/pointshop/lua/pointshop/sh_init.lua:119
     4. Initialize - addons/pointshop/lua/pointshop/sh_init.lua:55
      5. unknown - addons/pointshop/lua/autorun/pointshop.lua:4

L 10/29/2015 - 11:39:29: Lua Error: [POINTSHOP] Item missing name: weapons/M24.lua

[POINTSHOP] Item missing name: weapons/M24.lua

**Comment by Zafiro2232** [comment]
all of this should be fixed, simple typo.
