### ISSUE TITLE
benchmark fresh join times

### ISSUE THREAD

**Issue by Bryantdl7** [Bryantdl7/darkstormdev#156]
how long does it take vs someone with all the addons?

**Comment by Bryantdl7** [comment]
it seems like it takes me around 10 minutes but I need additional testing, i want to get both linux load times and windows load times. I will also try and get worst case scenario load times...

**Comment by Zafiro2232** [comment]
Stats
CPU: i7 4820k @ 3.7ghz
GPU: MSI GTX 760 2GB
RAM: 16GB DDR3 @ 1600mhz
115.41 Down 10.28 Up

┌──────────────────────┐
│  Ver: 64bit w/ chromium binaries     │   
├──────────────────────┤
│-Rejoining with all addons                │
│14/40 Players                                  │
│Result - 1m30s                                │
├──────────────────────┤
│-Allow all custom files fresh join       │
│12/40 Players                                  │
│Result - 3m 49s                               │
└──────────────────────┘
