### ISSUE TITLE
Make ulx cmds more organized

### ISSUE THREAD

**Issue by Bryantdl7** [Bryantdl7/darkstormdev#16]
currently there is way too many tabs, start organizing custom commands into the utilities/fun tabs.

**Comment by linkjay1** [comment]
honestly this is pretty gay mate

**Comment by Bryantdl7** [comment]
come on bro lets get this ball rolling

**Comment by linkjay1** [comment]
really time consuming but is pretty low on the agenda

will get to this when i need to burn some time

**Comment by Bryantdl7** [comment]
Maybe we could have @Zafiro2232  do this?

**Comment by Zafiro2232** [comment]
Would give it a try, need the servers ULX copy.

**Comment by linkjay1** [comment]
Zafiro is now working on this.

**Comment by linkjay1** [comment]
Suhfireo did it! Great work to this solid lad.
