### ISSUE TITLE
vote for alltalk setting ability

### ISSUE THREAD

**Issue by Bryantdl7** [Bryantdl7/darkstormdev#18]
!alltalk for example
vote for option 3(all players global)
vote for option 2(all players local chat only)
4 minute delay before people can use the command

Make this command usable for anyone, not just admins please

**Comment by Kang29** [comment]
0814100938.kb@gmail.com​

**Comment by Bryantdl7** [comment]
??? Who are you

**Comment by Bryantdl7** [comment]
http://imgur.com/LV9wVu1.jpg

**Comment by Kang29** [comment]
Local

**Comment by linkjay1** [comment]
ez.

basic plan

- take the vote command 

- take from the rcon command

if vote is more yes then it runs the rcon command alltalk 1|2|3

**Comment by Bryantdl7** [comment]
except only alltalk 3 and 2

**Comment by Bryantdl7** [comment]
bump

**Comment by linkjay1** [comment]
Complicated vote functions are complicated.

Delayed for a bit

**Comment by linkjay1** [comment]
Made it. Added to build. Did some extensive tests, works great. Fuck off.
