### ISSUE TITLE
Nolag issue

### ISSUE THREAD

**Issue by Bryantdl7** [Bryantdl7/darkstormdev#2]
Lua Error: [ERROR] addons/ulx mods/lua/ulx/modules/sh/nolag.lua:14: Tried to use a NULL physics object! 
1. EnableMotion - [C]:-1 
2. call - addons/ulx mods/lua/ulx/modules/sh/nolag.lua:14 
3. __fn - addons/ulib/lua/ulib/shared/commands.lua:942 
4. unknown - addons/ulib/lua/ulib/shared/commands.lua:1295 
5. Run - lua/includes/modules/concommand.lua:54 
6. unknown - addons/ulib/lua/ulib/shared/commands.lua:1309 
7. unknown - lua/includes/modules/concommand.lua:54

**Comment by Zafiro2232** [comment]
This is referring to freezing props with no physics apparently, the isvalid checks are also there.

**Comment by Bryantdl7** [comment]
this happens on gm_bigcity only. if that helps
