### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by Bryantdl7** [Bryantdl7/darkstormdev#20]
workshop/lua/entities/gmod_wire_screen.lua:123: bad argument #1 to 'GetTextSize' (string expected, got boolean)
stack traceback:
	[C]: in function 'GetTextSize'
	workshop/lua/entities/gmod_wire_screen.lua:123: in function 'DrawNumber'
	workshop/lua/entities/gmod_wire_screen.lua:160: in function <workshop/lua/entities/gmod_wire_screen.lua:152>
	[C]: in function 'xpcall'
	workshop/lua/wire/gpulib.lua:320: in function 'RenderToWorld'
	workshop/lua/entities/gmod_wire_screen.lua:152: in function <workshop/lua/entities/gmod_wire_screen.lua:149>workshop/lua/entities/gmod_wire_screen.lua:123: bad argument #1 to 'GetTextSize' (string expected, got boolean)
stack traceback:
	[C]: in function 'GetTextSize'
	workshop/lua/entities/gmod_wire_screen.lua:123: in function 'DrawNumber'
	workshop/lua/entities/gmod_wire_screen.lua:160: in function <workshop/lua/entities/gmod_wire_screen.lua:152>
	[C]: in function 'xpcall'
	workshop/lua/wire/gpulib.lua:320: in function 'RenderToWorld'
	workshop/lua/entities/gmod_wire_screen.lua:152: in function <workshop/lua/entities/gmod_wire_screen.lua:149>workshop/lua/entities/gmod_wire_screen.lua:123: bad argument #1 to 'GetTextSize' (string expected, got boolean)
stack traceback:
	[C]: in function 'GetTextSize'
	workshop/lua/entities/gmod_wire_screen.lua:123: in function 'DrawNumber'
	workshop/lua/entities/gmod_wire_screen.lua:160: in function <workshop/lua/entities/gmod_wire_screen.lua:152>
	[C]: in function 'xpcall'
	workshop/lua/wire/gpulib.lua:320: in function 'RenderToWorld'
	workshop/lua/entities/gmod_wire_screen.lua:152: in function <workshop/lua/entities/gmod_wire_screen.lua:149>workshop/lua/entities/gmod_wire_screen.lua:123: bad argument #1 to 'GetTextSize' (string expected, got boolean)
stack traceback:
	[C]: in function 'GetTextSize'
	workshop/lua/entities/gmod_wire_screen.lua:123: in function 'DrawNumber'
	workshop/lua/entities/gmod_wire_screen.lua:160: in function <workshop/lua/entities/gmod_wire_screen.lua:152>
	[C]: in function 'xpcall'
	workshop/lua/wire/gpulib.lua:320: in function 'RenderToWorld'
	workshop/lua/entities/gmod_wire_screen.lua:152: in function <workshop/lua/entities/gmod_wire_screen.lua:149>workshop/lua/entities/gmod_wire_screen.lua:123: bad argument #1 to 'GetTextSize' (string expected, got boolean)
stack traceback:
	[C]: in function 'GetTextSize'
	workshop/lua/entities/gmod_wire_screen.lua:123: in function 'DrawNumber'
	workshop/lua/entities/gmod_wire_screen.lua:160: in function <workshop/lua/entities/gmod_wire_screen.lua:152>
	[C]: in function 'xpcall'
	workshop/lua/wire/gpulib.lua:320: in function 'RenderToWorld'
	workshop/lua/entities/gmod_wire_screen.lua:152: in function <workshop/lua/entities/gmod_wire_screen.lua:149>workshop/lua/entities/gmod_wire_screen.lua:123: bad argument #1 to 'GetTextSize' (string expected, got boolean)
stack traceback:
	[C]: in function 'GetTextSize'
	workshop/lua/entities/gmod_wire_screen.lua:123: in function 'DrawNumber'
	workshop/lua/entities/gmod_wire_screen.lua:160: in function <workshop/lua/entities/gmod_wire_screen.lua:152>
	[C]: in function 'xpcall'
	workshop/lua/wire/gpulib.lua:320: in function 'RenderToWorld'
	workshop/lua/entities/gmod_wire_screen.lua:152: in function <workshop/lua/entities/gmod_wire_screen.lua:149>workshop/lua/entities/gmod_wire_screen.lua:123: bad argument #1 to 'GetTextSize' (string expected, got boolean)
stack traceback:
	[C]: in function 'GetTextSize'
	workshop/lua/entities/gmod_wire_screen.lua:123: in function 'DrawNumber'
	workshop/lua/entities/gmod_wire_screen.lua:160: in function <workshop/lua/entities/gmod_wire_screen.lua:152>
	[C]: in function 'xpcall'
	workshop/lua/wire/gpulib.lua:320: in function 'RenderToWorld'
	workshop/lua/entities/gmod_wire_screen.lua:152: in function <workshop/lua/entities/gmod_wire_screen.lua:149>workshop/lua/entities/gmod_wire_screen.lua:123: bad argument #1 to 'GetTextSize' (string expected, got boolean)
stack traceback:
	[C]: in function 'GetTextSize'
	workshop/lua/entities/gmod_wire_screen.lua:123: in function 'DrawNumber'
	workshop/lua/entities/gmod_wire_screen.lua:160: in function <workshop/lua/entities/gmod_wire_screen.lua:152>
	[C]: in function 'xpcall'
	workshop/lua/wire/gpulib.lua:320: in function 'RenderToWorld'
	workshop/lua/entities/gmod_wire_screen.lua:152: in function <workshop/lua/entities/gmod_wire_screen.lua:149>workshop/lua/entities/gmod_wire_screen.lua:123: bad argument #1 to 'GetTextSize' (string expected, got boolean)
stack traceback:
	[C]: in function 'GetTextSize'
	workshop/lua/entities/gmod_wire_screen.lua:123: in function 'DrawNumber'
	workshop/lua/entities/gmod_wire_screen.lua:160: in function <workshop/lua/entities/gmod_wire_screen.lua:152>
	[C]: in function 'xpcall'
	workshop/lua/wire/gpulib.lua:320: in function 'RenderToWorld'
	workshop/lua/entities/gmod_wire_screen.lua:152: in function <workshop/lua/entities/gmod_wire_screen.lua:149>workshop/lua/entities/gmod_wire_screen.lua:123: bad argument #1 to 'GetTextSize' (string expected, got boolean)
stack traceback:
	[C]: in function 'GetTextSize'
	workshop/lua/entities/gmod_wire_screen.lua:123: in function 'DrawNumber'
	workshop/lua/entities/gmod_wire_screen.lua:160: in function <workshop/lua/entities/gmod_wire_screen.lua:152>
	[C]: in function 'xpcall'
	workshop/lua/wire/gpulib.lua:320: in function 'RenderToWorld'
	workshop/lua/entities/gmod_wire_screen.lua:152: in function <workshop/lua/entities/gmod_wire_screen.lua:149>workshop/lua/entities/gmod_wire_screen.lua:123: bad argument #1 to 'GetTextSize' (string expected, got boolean)
stack traceback:
	[C]: in function 'GetTextSize'
	workshop/lua/entities/gmod_wire_screen.lua:123: in function 'DrawNumber'
	workshop/lua/entities/gmod_wire_screen.lua:160: in function <workshop/lua/entities/gmod_wire_screen.lua:152>
	[C]: in function 'xpcall'
	workshop/lua/wire/gpulib.lua:320: in function 'RenderToWorld'
	workshop/lua/entities/gmod_wire_screen.lua:152: in function <workshop/lua/entities/gmod_wire_screen.lua:149>workshop/lua/entities/gmod_wire_screen.lua:123: bad argument #1 to 'GetTextSize' (string expected, got boolean)
stack traceback:
	[C]: in function 'GetTextSize'
	workshop/lua/entities/gmod_wire_screen.lua:123: in function 'DrawNumber'
	workshop/lua/entities/gmod_wire_screen.lua:160: in function <workshop/lua/entities/gmod_wire_screen.lua:152>
	[C]: in function 'xpcall'
	workshop/lua/wire/gpulib.lua:320: in function 'RenderToWorld'
	workshop/lua/entities/gmod_wire_screen.lua:152: in function <workshop/lua/entities/gmod_wire_screen.lua:149>workshop/lua/entities/gmod_wire_screen.lua:123: bad argument #1 to 'GetTextSize' (string expected, got boolean)
stack traceback:
	[C]: in function 'GetTextSize'
	workshop/lua/entities/gmod_wire_screen.lua:123: in function 'DrawNumber'
	workshop/lua/entities/gmod_wire_screen.lua:160: in function <workshop/lua/entities/gmod_wire_screen.lua:152>
	[C]: in function 'xpcall'
	workshop/lua/wire/gpulib.lua:320: in function 'RenderToWorld'
	workshop/lua/entities/gmod_wire_screen.lua:152: in function <workshop/lua/entities/gmod_wire_screen.lua:149>

**Comment by linkjay1** [comment]
When does this occur?

**Comment by Bryantdl7** [comment]
It occured randomly to my knowledge

**Comment by linkjay1** [comment]
Seems to not occur. If it happens again, reopen it with better information.
