### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Bryantdl7** [Bryantdl7/darkstormdev#21]
[ERROR] lua/includes/extensions/net.lua:182: net.ReadType: Couldn't read type 2
  1. error - [C]:-1
   2. ReadType - lua/includes/extensions/net.lua:182
    3. ReadType - lua/includes/extensions/net.lua:121
     4. ReadTable - lua/includes/extensions/net.lua:124
      5. func - addons/gban/lua/gban/client/cl_networking.lua:20
       6. unknown - lua/includes/extensions/net.lua:32

[ERROR] lua/includes/extensions/net.lua:182: net.ReadType: Couldn't read type 210
  1. error - [C]:-1
   2. ReadType - lua/includes/extensions/net.lua:182
    3. ReadType - lua/includes/extensions/net.lua:124
     4. ReadTable - lua/includes/extensions/net.lua:124
      5. func - addons/gban/lua/gban/client/cl_networking.lua:30
       6. unknown - lua/includes/extensions/net.lua:32
****

**Comment by linkjay1** [comment]
Devs are on it
