### ISSUE TITLE
nolag issue

### ISSUE THREAD

**Issue by Bryantdl7** [Bryantdl7/darkstormdev#22]
1. EnableMotion - [C]:-1
            2. call - addons/ulx mods/lua/ulx/modules/sh/nolag.lua:30
             3. __fn - addons/ulib/lua/ulib/shared/commands.lua:943
              4. unknown - addons/ulib/lua/ulib/shared/commands.lua:1296
               5. unknown - lua/includes/modules/concommand.lua:54
         
         
         
         [ERROR] addons/ulx mods/lua/ulx/modules/sh/nolag.lua:30: Tried to use a NULL physics object!
           1. EnableMotion - [C]:-1
            2. call - addons/ulx mods/lua/ulx/modules/sh/nolag.lua:30
             3. __fn - addons/ulib/lua/ulib/shared/commands.lua:943
              4. unknown - addons/ulib/lua/ulib/shared/commands.lua:1296
               5. unknown - lua/includes/modules/concommand.lua:54

**Comment by Bryantdl7** [comment]
see darkstormdev/issues/8

**Comment by Bryantdl7** [comment]
#8

**Comment by linkjay1** [comment]
All that was needed was a server restart.

Fixxxxxxxxxxed.

**Comment by Bryantdl7** [comment]
no

**Comment by linkjay1** [comment]
It's fixed so i am going to re close this. Please don't re open it.
