### ISSUE TITLE
improve afk

### ISSUE THREAD

**Issue by Bryantdl7** [Bryantdl7/darkstormdev#24]
currently afk asks everyone EVERY 20 minutes they play if they are afk. It needs to start the timer when they have not been moving for a while instead.

**Comment by Bryantdl7** [comment]
New idea, lets just modify ulx afk with the button this noob uses. I uploaded ulx afk for referencing.

**Comment by Bryantdl7** [comment]
so the button will have the same stop as this crappy addon, but all the benefits of ulx afk

**Comment by linkjay1** [comment]
y u assign zippo>

tuf luv 5 me </3 :'(

**Comment by Bryantdl7** [comment]
Because you seem busy with other projects, feel free to reassign yourself

**Comment by linkjay1** [comment]
1:31 PM - [DSTM] linkjay1: Hm
1:31 PM - [DSTM] linkjay1: Just going to look for a better AFK addon
1:31 PM - [DSTM] linkjay1: This one is too under developed
1:31 PM - [DSTM] linkjay1: The GUI is going to fuck everyone up in the first place
1:32 PM - [DSTM] linkjay1: I would have to decompile any addon with a GUI in our addons and take the piece of code that closes that specific's addon's GUI
1:32 PM - [DSTM] linkjay1: And i would have to implement a bunch of functions that tell the addon to only work when the person is actually AFK
1:32 PM - [DSTM] linkjay1: like movement events and shit


This is my take on the addon. I say we should get a new AFK addon.

**Comment by linkjay1** [comment]
This one looks promising.

https://forums.ulyssesmod.net/index.php?topic=5963.0

**Comment by Bryantdl7** [comment]
that
is
what
i
uploaded

there
is
no
gui
so
pac
people
get
rek'd

Bryant.

**Comment by Bryantdl7** [comment]
add GUI function here?

https://github.com/Bryantdl7/darkstormdev/blob/master/addons/ULX_AFK/lua/ulx/modules/sh/aafk.lua#L40

**Comment by Bryantdl7** [comment]
Might be removing afk rule all together, will reopen if we keep the rule
