### ISSUE TITLE
update pointshop

### ISSUE THREAD

**Issue by Bryantdl7** [Bryantdl7/darkstormdev#3]
pointshop needs new weapons and the obsolete stuff removed

**Comment by Zafiro2232** [comment]
Could I be assigned to this? http://i.imgur.com/83QQ5PN.png Might also be able to work on hats, haven't tested anything as I don't have TF2 mounted.

**Comment by Bryantdl7** [comment]
Let me upload the files later so you know what you have to work with.

**Comment by Zafiro2232** [comment]
Ok, will either be working today or sleeping.

**Comment by Zafiro2232** [comment]
https://github.com/Zafiro2232/PSI

**Comment by Bryantdl7** [comment]
Why not upload the files to my github?

**Comment by Zafiro2232** [comment]
Only hade a code box, made a repos on mine and I could actually upload files

**Comment by Bryantdl7** [comment]
you need the github program

Bryant.

**Comment by Zafiro2232** [comment]
Figured out git, everything should be added properly.

**Comment by Zafiro2232** [comment]
I was assuming the old weapons folder would be scrapped, this is why the old weapons are still there and some of my changes aren't active

**Comment by Bryantdl7** [comment]
Yeah they didn't delete, I hope I have time to fix that tomorrow
