### ISSUE TITLE
Update votemap perms

### ISSUE THREAD

**Issue by Bryantdl7** [Bryantdl7/darkstormdev#32]
Currently votemaps dont show all available maps for staff. Needs to be fixed eventually. 

Maps to add: gm_construct_flatgrass_v6 functional flatgrass, warmap

**Comment by Bryantdl7** [comment]
Gonna see about traitorous doing this

**Comment by Bryantdl7** [comment]
@LordMechanist gm_construct_flatgrass_v6 functional flatgrass, warmap, any other suggestions of what should be added?

**Comment by AMechanist** [comment]
I think we're good on map permissions and maps, there was one map suggestion that got accepted in the Request section of the forums. I'll leave that to you @Bryantdl7, since my Internet is slower then a turtle unmotivated by life.

**Comment by Bryantdl7** [comment]
@Mar0n3  should've completed this. I will consider it complete when he closes it out.

**Comment by Mar0n3** [comment]
Ye sorry for the late reply. I sometimes forget about github
