### ISSUE TITLE
Enhancing maps

### ISSUE THREAD

**Issue by Bryantdl7** [Bryantdl7/darkstormdev#34]
gm_skydive2008_rc1
gm_ragdoll_slaughter_v4
gm_hsd_reallybigmap

**Comment by Zafiro2232** [comment]
I will work on skydive for now, from what I can tell saving and editing is almost a waste of time.

**Comment by Bryantdl7** [comment]
What do you mean saving and editing is a waste of time?

**Comment by Zafiro2232** [comment]
I'm extremely late because I do thing sporadically, anyhow I will have to reconstruct most of the map except for maybe the airplane.

**Comment by Bryantdl7** [comment]
Post some milestones as you get stuff done. Again it's a low priority task, so just take your time and keep this updated

**Comment by Zafiro2232** [comment]
I try and manage all of my progress here https://trello.com/b/01PdH8L7, focusing on more than one map at a time tends to be overwhelming.

**Comment by Bryantdl7** [comment]
Are we scrapping this?

**Comment by AMechanist** [comment]
I think we lack the manpower to really put our all into enhancing maps, and the reward (Player Increase, etc.) we'd get for it is nonexistent since players seem to be content with our current generic maps
