### ISSUE TITLE
Gmod does not recognize players are admin

### ISSUE THREAD

**Issue by Bryantdl7** [Bryantdl7/darkstormdev#39]
Most commonly noticed with rank of owner. Might be the reason people can't spawn keypad cracker too.

**Comment by Zafiro2232** [comment]
This does tie back to the keypad cracker issue, you will also notice you can't spawn the flechette gun.

**Comment by linkjay1** [comment]
Someone doesn't know how to properly do ULX permissions. I fixed this a while ago when I fixed ULX inheritance that someone fucked up.
