### ISSUE TITLE
The Search function is non-functional

### ISSUE THREAD

**Issue by SparkyTM** [Bryantdl7/darkstormdev#54]
The Search function is non-functional,
try and recreate the error i get :l

https://forums.darkstormservers.com/index.php?action=search

The error:
https://forums.darkstormservers.com/index.php?action=search2

This also affects the searchbars in the staff and other centers.

**Comment by Bryantdl7** [comment]
Definitely an issue. We do have a planned solution for this soon. 

![image](https://user-images.githubusercontent.com/5564661/35812468-05908f0a-0a5f-11e8-89bd-c1049f2628d5.png)

**Comment by Bryantdl7** [comment]
This is being continued in #60. Locking comments since progress will take place there.
