### ISSUE TITLE
homepage Login is non functional

### ISSUE THREAD

**Issue by SparkyTM** [Bryantdl7/darkstormdev#66]
ok, so if you go to the sites homepage:
https://forums.darkstormservers.com/index.php ,

And sign in using the box at the left-hand box:
![info](https://user-images.githubusercontent.com/35932846/36078915-addf9298-0f85-11e8-9cf9-96334690935e.png)

The following error is given:
https://forums.darkstormservers.com/index.php?action=login2

EDIT: you need to be logged out to see the error mssg.

**Comment by Bryantdl7** [comment]
Thanks for pointing this out. the temporary fix to this is using the login
button on the top of the home page.

Bryant.
