### ISSUE TITLE
Moderate tab on site.

### ISSUE THREAD

**Issue by SparkyTM** [Bryantdl7/darkstormdev#67]
Ok so when you hover your mouse over the moderate tab on Google Chrome:
![mod error 1](https://user-images.githubusercontent.com/35932846/37165044-51f31256-2304-11e8-807c-5def52f58218.png)

This Issue with the dropdown menu is present:
![error 2](https://user-images.githubusercontent.com/35932846/37165215-be557786-2304-11e8-8e37-ff4e3200d4dc.png)

Sorta makes the menu useless, but then again, ive never used it.
The other staff might tho :p

Im using Version 65.0.3325.146 (Official Build) (64-bit) Of chrome, which is the latest build.

**Comment by Bryantdl7** [comment]
Its an issue specific to the theme. All buttons still work just hover over them to see where they lead
