### ISSUE TITLE
ulx_afk onscreen warning

### ISSUE THREAD

**Issue by Bryantdl7** [Bryantdl7/darkstormdev#7]
similar to the auto reconnect script i'd like to have a pop up warning they will be kicked in 5 minutes if they don't click ok. this will stop people using pac from being kicked. 
See https://github.com/Bryantdl7/darkstormdev/blob/master/lua/autorun/sh_anticrash.lua#L98

**Comment by Zafiro2232** [comment]
ulx_afk was removed.
