### ISSUE TITLE
Addon Request: Enhanced Playermodel Selector

### ISSUE THREAD

**Issue by InvidiousVoid** [Bryantdl7/darkstormdev#77]
https://steamcommunity.com/sharedfiles/filedetails/?id=193803413

**Comment by Dreamurrrr** [comment]
This is a mandatory one lol.

**Comment by Bryantdl7** [comment]
I’ll add it back in now. Please let me know if anything changes performance wise over the next day

**Comment by Bryantdl7** [comment]
This is for an addon called super freeze. Please resubmit your request with the proper URL.

**Comment by InvidiousVoid** [comment]
Sorry about the wrong link.. lol.
