### ISSUE TITLE
Addon Request: Unbreakable Tool

### ISSUE THREAD

**Issue by InvidiousVoid** [Bryantdl7/darkstormdev#78]
https://steamcommunity.com/sharedfiles/filedetails/?id=111158387

**Comment by Bryantdl7** [comment]
I’ll add this now. Please confirm if there is any changes in performance when I add this in.

**Comment by InvidiousVoid** [comment]
Has it been added yet? I have not seen any changes.

**Comment by Bryantdl7** [comment]
I’ll try and trigger a server reboot now.
