### ISSUE TITLE
Addon Request: Outfitter Multiplayer Playermodels

### ISSUE THREAD

**Issue by InvidiousVoid** [Bryantdl7/darkstormdev#79]
https://steamcommunity.com/sharedfiles/filedetails/?id=882463775

**Comment by Dreamurrrr** [comment]
Yes, we should add this back.

**Comment by Velcroisntniceiguess** [comment]
would say yes, however the tiny playermodels that by the PAC Size rule, would be against the rules are getting pretty annoying.

**Comment by Dreamurrrr** [comment]
Then report the player that is abusing it to staff. We had this add-on for the longest time and we had no issues with it.

**Comment by Zafiro2232** [comment]
Bryant re-added.
