### ISSUE TITLE
nolag error

### ISSUE THREAD

**Issue by Bryantdl7** [Bryantdl7/darkstormdev#8]
13:13:55 [ERROR] addons/ulx mods/lua/ulx/modules/sh/nolag.lua:30: Tried to use a NULL physics object!
           1. EnableMotion - [C]:-1
            2. call - addons/ulx mods/lua/ulx/modules/sh/nolag.lua:30
             3. __fn - addons/ulib/lua/ulib/shared/commands.lua:942
              4. unknown - addons/ulib/lua/ulib/shared/commands.lua:1295
               5. unknown - lua/includes/modules/concommand.lua:54
         
         
         
         [ERROR] addons/ulx mods/lua/ulx/modules/sh/nolag.lua:30: Tried to use a NULL physics object!
           1. EnableMotion - [C]:-1
            2. call - addons/ulx mods/lua/ulx/modules/sh/nolag.lua:30
             3. __fn - addons/ulib/lua/ulib/shared/commands.lua:942
              4. unknown - addons/ulib/lua/ulib/shared/commands.lua:1295
               5. unknown - lua/includes/modules/concommand.lua:54

https://github.com/Bryantdl7/darkstormdev/blob/master/addons/ulx%20mods/lua/ulx/modules/sh/nolag.lua

**Comment by Bryantdl7** [comment]
Any update on progress for this?

**Comment by Zafiro2232** [comment]
I think I found a fix, quoting rubat or robotboy655 : Add IsValid check to your "phys" variable, the physics object will not exist for the error model ( or models without physics ) hence why the error occurs when you try to use an invalid physics object. I'm guessing the stopmotion is being run on something like effects, all though I have never seen this error

**Comment by Zafiro2232** [comment]
Just took a look at the code, the author individually wrote down which entities should be frozen this erro r doesn't make much sense. Line 30 is telling the server to freeze gmod_lights

**Comment by Bryantdl7** [comment]
That's legitimenty's work.

**Comment by Zafiro2232** [comment]
I wasn't completely sure, --/*-------------------------------------------------------------------------------------------------------------------------
--Freeze every prop/player/LightEnt. on the server!
--Made By HeLLFox_15,
--edited by Bryantdl7 to work in xgui nicer
--Improved by Ligitmenty (Note: THIS IS A SNAPSHOT PRODUCT, EXPECT BUGS)
---------------------------------------------------------------------------

**Comment by Bryantdl7** [comment]
Lol @ligitimenty
