### ISSUE TITLE
Addon Request: Sligwolf's Train Cars

### ISSUE THREAD

**Issue by InvidiousVoid** [Bryantdl7/darkstormdev#83]
https://steamcommunity.com/sharedfiles/filedetails/?id=379538128

**Comment by Bryantdl7** [comment]
I am pretty sure a large amount of our lag came from this addon, due to people making extremely long trains using it. I'll still consider, just going to focus on other addons in the meantime.

**Comment by Zafiro2232** [comment]
Worth adding, but keep the trains small.
