### ISSUE TITLE
Addon Request: Superfreeze

### ISSUE THREAD

**Issue by InvidiousVoid** [Bryantdl7/darkstormdev#84]
https://steamcommunity.com/sharedfiles/filedetails/?id=193803413

**Comment by Dreamurrrr** [comment]
This can actually help with lag. Read the description.

**Comment by Bryantdl7** [comment]
I’ll look into this one definitely. Slowly adding addons in so feel free to stay subscribed to the progress of this ticket

**Comment by InvidiousVoid** [comment]
Hey if you can make this high priority. I would love to see it in game. Works wonders on props.
