### ISSUE TITLE
[pointshop] errors in models

### ISSUE THREAD

**Issue by Bryantdl7** [Bryantdl7/darkstormdev#9]
![image](https://cloud.githubusercontent.com/assets/5564661/10642832/c25223da-77ed-11e5-9334-46400c8bb2a7.png)

**Comment by Zafiro2232** [comment]
Just need to transfer pointshop to fas:2

**Comment by Zafiro2232** [comment]
Fixing this now, just noticed it is m9k specialties and they were removed.
