### ISSUE TITLE
RT Camera

### ISSUE THREAD

**Issue by Dreamurrrr** [Bryantdl7/darkstormdev#90]
https://steamcommunity.com/sharedfiles/filedetails/?id=106944414

**Comment by Velcroisntniceiguess** [comment]
already comes with wire

**Comment by Dreamurrrr** [comment]
It doesn't appear in the camera category.

**Comment by Bryantdl7** [comment]
It should be in the wire tab. Take a look and see if it’s in there.

**Comment by Dreamurrrr** [comment]
I'll do that after I come back from school. Anyone can confirm for me in the meanwhile.

**Comment by InvidiousVoid** [comment]
RT Camera is in the wire tab. Confirmed working. You may now close this, @Dreamurrrr @Bryantdl7 
Although it would be cool if we had another camera like RT Camera where it was per-user instead of 1 RT Camera across server. If we can find one, I would love it.

**Comment by Bryantdl7** [comment]
Isn’t there a way with the numpad keys to choose different camera inputs? Either way, thanks for the confirmation

**Comment by Dreamurrrr** [comment]
One more thing I would like to be also confirmed, can you create a display for the RT camera? It is primarily used to put camera views on displays, so I want to make sure that works, @InvidiousVoid. 

To create a display for it you can:
-spawn the phx monitor (it's in Q > Browse > Games > Garry's Mod > props_phx if you dont have phx spawnlists)
-use the on screen monitor built into the tool's menu
-set the material of any prop (small-medium square plates generally work well) to rendertarget

Try all three methods please, and report which one, if any, worked.

**Comment by Dreamurrrr** [comment]
Can you reopen this issue? He forgot to test the displays @Bryantdl7

**Comment by InvidiousVoid** [comment]
Just now seen this and won't be able to do any testing until some time tomorrow. Wire RT cam did work when toggling and on the toolgun preview. I am not sure about materials though.

**Comment by Dreamurrrr** [comment]
I'll check the materials today when I get back from school.

**Comment by InvidiousVoid** [comment]
RT Camera material works. (Rendertarget)

**Comment by Dreamurrrr** [comment]
@InvidiousVoid how about the monitor?

**Comment by Dreamurrrr** [comment]
Confirmed monitor is in the game. Closing.
