### ISSUE TITLE
3D Stream Radio

### ISSUE THREAD

**Issue by Dreamurrrr** [Bryantdl7/darkstormdev#91]
https://steamcommunity.com/sharedfiles/filedetails/?id=246756300

**Comment by Dreamurrrr** [comment]
(we should only allow it for anyone above the player rank because you don't have to interact with it in order to hear it)

**Comment by Pato0101** [comment]
this seems like a cool addition

**Comment by Ohdesza** [comment]
this would be nice

**Comment by Dreamurrrr** [comment]
Also, I highly recommend turning on youtube urls

**Comment by Zafiro2232** [comment]
Added with no issues.
