### ISSUE TITLE
Tank Tracks

### ISSUE THREAD

**Issue by Bonnie603** [Bryantdl7/darkstormdev#92]
https://steamcommunity.com/sharedfiles/filedetails/?id=737640184

**Comment by Bonnie603** [comment]
we should have for builders to use for vehicles or details

**Comment by Dreamurrrr** [comment]
This is necessary for tanks to work.

**Comment by Bryantdl7** [comment]
I’ll add this soon, I just need to ensure that there are no conflicts with other addons I have installed.
