### ISSUE TITLE
Request: Melee Arts 2

### ISSUE THREAD

**Issue by Backcats-Tottally-Tubular** [Bryantdl7/darkstormdev#95]
https://steamcommunity.com/sharedfiles/filedetails/?id=1825542758&searchtext=melee+arts

I request this on the forums, got over 70%. so uber-lame-sauce that a server wipe happened.
![Melee arts 2](https://user-images.githubusercontent.com/54675402/63948961-a3bbe680-ca47-11e9-8624-705854c2cf8e.png)

**Comment by Dreamurrrr** [comment]
The link is a CoD screenshot...

**Comment by Backcats-Tottally-Tubular** [comment]
wtf, was a direct link to the addon

**Comment by Dreamurrrr** [comment]
Well, edit the link then with the correct one.

**Comment by Dreamurrrr** [comment]
Link is fixed!

**Comment by Dreamurrrr** [comment]
Tbh, I really don't like this addon, but that is just me.

**Comment by Bryantdl7** [comment]
Addons like this I always worry about clashing performance. I’ll stoll consider it but I’m going to give it lower priority for now to ensure we stay at low lag

**Comment by Bryantdl7** [comment]
Lower priority meaning a few days from now as opposed to other addons—-

**Comment by Dreamurrrr** [comment]
Looking at the description, this looks like an add-on that may lag the server due to how much it implements onto the player. It even has its own entire system for backstabs and bosses. I don't think the server can be stable on that.

**Comment by Pato0101** [comment]
coolio addon,but again,as bryant said it might cause lag,like if it doesnt cause lag then sure

**Comment by Zafiro2232** [comment]
Added and works fine.
