### ISSUE TITLE
PlayX

### ISSUE THREAD

**Issue by Dreamurrrr** [Bryantdl7/darkstormdev#96]
https://steamcommunity.com/sharedfiles/filedetails/?id=106516163
Alernative to Media Player (#81).
Used it before and it is pretty good.

**Comment by Dreamurrrr** [comment]
Note this addon does not work on Mac. Reading the description is also highly recommend.

**Comment by Zafiro2232** [comment]
Bryant added this

**Comment by Dreamurrrr** [comment]
They are blocked. 
https://media.discordapp.net/attachments/399113762583347210/617130025082421258/unknown.png
@Bryantdl7 @Zafiro2232

**Comment by Bryantdl7** [comment]
Working on this now

**Comment by Bryantdl7** [comment]
gm+ have this
