### ISSUE TITLE
Dark UI Spawnmenu

### ISSUE THREAD

**Issue by Dreamurrrr** [Bryantdl7/darkstormdev#97]
https://steamcommunity.com/sharedfiles/filedetails/?id=888392108

**Comment by InvidiousVoid** [comment]
Hey man I'm all for this, as long as there can be a toggle of some sort incase the menu doesn't load/work right.

**Comment by Bryantdl7** [comment]
I intentionally removed this because it was so damn dark. Is there a way to disable this if people don’t want it?

**Comment by Dreamurrrr** [comment]
I will check.

**Comment by Dreamurrrr** [comment]
I submitted a discussion for the issue on the add-on: https://steamcommunity.com/workshop/filedetails/discussion/888392108/1636417554418865252/

**Comment by Dreamurrrr** [comment]
I recommend working on other add-ons while we wait for a response.

**Comment by Bryantdl7** [comment]
Feel free to reply if you ever hear back on that feature.

**Comment by Dreamurrrr** [comment]
Great news! The add-on author actually listened! He added a command to disable it client side. Here is his response, @Bryantdl7:
![Steam_U91RJ8HMFF](https://user-images.githubusercontent.com/21233238/64463468-cabe8c00-d0c9-11e9-9ed0-f63b87e19419.png)
