### ISSUE TITLE
Drivable Jetski Kawasaki

### ISSUE THREAD

**Issue by Dreamurrrr** [Bryantdl7/darkstormdev#99]
Just a wave runner.
https://steamcommunity.com/sharedfiles/filedetails/?id=105908087

**Comment by Pato0101** [comment]
my opinionion is that this would be a cool addon to have in the water maps,but lately we havent been really...changing the map.i would want it to change but it dont

**Comment by Zafiro2232** [comment]
Gonna have to remove this one as it crashes people without the addon
